apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.112.0
          args:
            - "--config=/etc/otel/otel-collector-config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config